#======================================================================
#    "Mixed Finite Element Methods for Coupled 3D/1D Fluid Curved Problems"
#        Course on Advanced Programming for Scientific Computing
#                      Politecnico di Milano
#                          A.Y. 2016-2017
#                  
#               Copyright (C) 2017 Giorgio Raimondi
#======================================================================
# 
#  @file   Makefile
#  @author Giorgio Raimondi <giorgio3.raimondi@mail.polimi.it>
#  @date   May 2017.
#
#======================================================================    
.PHONY= all clean distclean
.DEFAULT_GOAL=all



all:
	make -C include

clean:
	make clean -C include

distclean: clean
	make distclean	-C include
